export interface DuelsStats {
	games_played_duels: number
	duels_winstreak_best_uhc_duel: number
	rematch_option_1: string
	duels_recently_played: string
	sw_duels_kit_1: string
	kit_menu_option: string
	duels_winstreak_best_sw_duel: number
	sw_duels_kit: string
	duels_winstreak_best_op_duel: number
	mw_duels_class: string
	duels_winstreak_best_mw_duel: number
	duels_winstreak_best_combo_duel: number
	duels_winstreak_best_potion_duel: number
	sw_duel_layout_blacksmith: DuelsInventoryLayout
	show_lb_option: string
	duels_winstreak_best_op_doubles: number
	duels_winstreak_best_classic_duel: number
	duels_winstreak_classic_duel: number
	duels_winstreak_best_sw_doubles: number
	duels_showqueuebook: boolean
	mw_duels_class_1: string
	mw_duel_layout_moleman_4: DuelsInventoryLayout
	sw_duel_layout_scout_4: DuelsInventoryLayout
	uhc_duel_layout_4: DuelsInventoryLayout
	duels_winstreak_best_uhc_four: number
	duels_winstreak_uhc_four: number
	duels_winstreak_mw_duel: number
	bow_duel_layout_5: DuelsInventoryLayout
	potion_duel_layout_4: DuelsInventoryLayout
	sw_duel_layout_athlete_4: DuelsInventoryLayout
	sw_duel_layout_blacksmith_4: DuelsInventoryLayout
	sw_duel_layout_pyromancer_4: DuelsInventoryLayout
	mw_duel_layout_herobrine_5: DuelsInventoryLayout
	mw_duel_layout_arcanist_5: DuelsInventoryLayout
	duels_winstreak_best_uhc_doubles: number
	duels_winstreak_uhc_doubles: number
	sw_duel_layout_scout_5: DuelsInventoryLayout
	duels_winstreak_uhc_duel: number
	melee_swings_duels: number
	sw_duel_melee_swings_duels: number
	sw_duel_damage_dealt_duels: number
	sw_duel_melee_hits_duels: number
	melee_hits_duels: number
	damage_dealt_duels: number
	sw_duel_health_regenerated_duels: number
	health_regenerated_duels: number
	melee_swings: number
	duels_melee_swings: number
	sw_duel_duels_melee_swings: number
	sw_duel_melee_swings: number
	melee_hits: number
	sw_duel_damage_dealt: number
	damage_dealt: number
	sw_duel_melee_hits: number
	sw_duel_bow_hits: number
	bow_hits: number
	sw_duel_bow_shots: number
	health_regenerated: number
	sw_duel_health_regenerated: number
	bow_shots: number
	sw_duel_rounds_played: number
	rounds_played: number
	wins: number
	sw_duel_wins: number
	kills: number
	sw_duel_kills: number
	losses: number
	sw_duel_losses: number
	deaths: number
	sw_duel_deaths: number
	uhc_duel_health_regenerated: number
	uhc_duel_melee_swings: number
	uhc_duel_kills: number
	uhc_duel_rounds_played: number
	uhc_duel_damage_dealt: number
	uhc_duel_wins: number
	uhc_duel_melee_hits: number
	uhc_duel_losses: number
	uhc_duel_bow_shots: number
	uhc_duel_bow_hits: number
	uhc_duel_deaths: number
	sw_duel_layout_baseball_player_5: DuelsInventoryLayout
	mw_doubles_health_regenerated: number
	mw_doubles_rounds_played: number
	mw_doubles_deaths: number
	mw_doubles_losses: number
	op_doubles_wins: number
	op_doubles_rounds_played: number
	uhc_tournament_kills: number
	uhc_tournament_melee_swings: number
	uhc_tournament_rounds_played: number
	uhc_tournament_melee_hits: number
	uhc_tournament_damage_dealt: number
	uhc_tournament_wins: number
	uhc_tournament_losses: number
	op_duel_damage_dealt: number
	op_duel_kills: number
	op_duel_melee_swings: number
	op_duel_melee_hits: number
	op_duel_bow_shots: number
	op_duel_health_regenerated: number
	op_duel_wins: number
	op_duel_rounds_played: number
	op_duel_bow_hits: number
	op_duel_deaths: number
	op_duel_losses: number
	uhc_tournament_health_regenerated: number
	uhc_tournament_deaths: number
	uhc: boolean
	challenges_enabled: boolean
	mega_walls: boolean
	skywars: boolean
	no_debuff: boolean
	blitz: boolean
	op: boolean
	bow: boolean
	selected_1: string
	classic: boolean
	selected_2: string
	combo: boolean
	uhc_tournament_bow_hits: number
	uhc_tournament_bow_shots: number
	coins: number
	uhc_doubles_rounds_played: number
	uhc_doubles_melee_swings: number
	uhc_doubles_wins: number
	sw_doubles_melee_hits: number
	sw_doubles_melee_swings: number
	sw_doubles_rounds_played: number
	sw_doubles_health_regenerated: number
	sw_doubles_damage_dealt: number
	op_doubles_health_regenerated: number
	op_doubles_melee_hits: number
	op_doubles_damage_dealt: number
	op_doubles_bow_shots: number
	op_doubles_melee_swings: number
	sw_doubles_wins: number
	sw_doubles_kills: number
	uhc_doubles_health_regenerated: number
	uhc_doubles_deaths: number
	uhc_doubles_losses: number
	uhc_doubles_bow_hits: number
	uhc_doubles_melee_hits: number
	uhc_doubles_damage_dealt: number
	uhc_doubles_kills: number
	uhc_doubles_bow_shots: number
	bow_spleef_duel_bow_shots: number
	bow_spleef_duel_losses: number
	bow_spleef_duel_rounds_played: number
	duels_winstreak_best_bowspleef_duel: number
	bowspleef_duel_rounds_played: number
	bowspleef_duel_bow_shots: number
	bowspleef_duel_deaths: number
	bowspleef_duel_wins: number
	bowspleef_duel_losses: number
	bow_duel: boolean
	uhc_four: boolean
	mw_duel: boolean
	uhc_duel: boolean
	uhc_doubles: boolean
	op_duel: boolean
	classic_duel: boolean
	mw_doubles: boolean
	sw_duel: boolean
	mw_four: boolean
	sw_doubles: boolean
	combo_duel: boolean
	potion_duel: boolean
	op_doubles: boolean
	sw_duel_layout_armorsmith_5: DuelsInventoryLayout
	sw_tournament_health_regenerated: number
	sw_tournament_rounds_played: number
	sw_tournament_melee_hits: number
	sw_tournament_melee_swings: number
	sw_tournament_damage_dealt: number
	bowspleef_duel: boolean
	blitz_duels_kit: string
	blitz_duel_melee_swings: number
	blitz_duel_damage_dealt: number
	blitz_duel_melee_hits: number
	blitz_duel_bow_shots: number
	blitz_duel_rounds_played: number
	blitz_duel_wins: number
	blitz_duel_bow_hits: number
	blitz_duel_health_regenerated: number
	blitz_duel_kills: number
	blitz_duel_losses: number
	blitz_duel_deaths: number
	uhc_duel_layout_5: DuelsInventoryLayout
	duels_winstreak_best_blitz_duel: number
	combo_duel_melee_hits: number
	combo_duel_wins: number
	combo_duel_melee_swings: number
	combo_duel_rounds_played: number
	combo_duel_health_regenerated: number
	combo_duel_deaths: number
	combo_duel_losses: number
	combo_duel_kills: number
	sw_tournament_deaths: number
	sw_tournament_kills: number
	uhc_four_deaths: number
	uhc_four_health_regenerated: number
	uhc_four_melee_swings: number
	uhc_four_bow_hits: number
	uhc_four_melee_hits: number
	uhc_four_rounds_played: number
	uhc_four_damage_dealt: number
	uhc_four_kills: number
	uhc_four_bow_shots: number
	uhc_four_losses: number
	classic_duel_rounds_played: number
	classic_duel_losses: number
	classic_duel_deaths: number
	classic_duel_melee_hits: number
	classic_duel_kills: number
	classic_duel_health_regenerated: number
	classic_duel_damage_dealt: number
	classic_duel_bow_shots: number
	classic_duel_melee_swings: number
	classic_duel_wins: number
	classic_duel_bow_hits: number
	sw_tournament_bow_hits: number
	sw_tournament_bow_shots: number
	kit_wins: number
	sw_duel_salmon_kit_wins: number
	sw_duel_kit_wins: number
	salmon_kit_wins: number
	uhc_four_wins: number
	sw_doubles_deaths: number
	sw_doubles_losses: number
	scout_kit_wins: number
	sw_doubles_kit_wins: number
	sw_doubles_scout_kit_wins: number
	chat_enabled: string
	blitz_duel: boolean
	blitz_duel_layout_pigman_5: DuelsInventoryLayout
	bow_duel_bow_hits: number
	bow_duel_deaths: number
	bow_duel_losses: number
	bow_duel_bow_shots: number
	bow_duel_health_regenerated: number
	bow_duel_damage_dealt: number
	bow_duel_rounds_played: number
	duels_winstreak_best_bow_duel: number
	bow_duel_wins: number
	bow_duel_kills: number
	sw_duel_pyromancer_kit_wins: number
	pyromancer_kit_wins: number
	activeVictoryDance: string
	packages: string[]
	sw_duel_layout_paladin_5: DuelsInventoryLayout
	active_projectile_trail: string
	shop_sort: string
	duels_boxes: number
	shop_sort_enable_owned_first: boolean
	mw_duel_bow_shots: number
	mw_duel_losses: number
	mw_duel_deaths: number
	mw_duel_health_regenerated: number
	mw_duel_rounds_played: number
	progress_title: string
	goldenhead_skin: string
	cosmetictitle: string
	op_doubles_kills: number
	op_doubles_deaths: number
	op_doubles_losses: number
	active_emblem: string
	sumo_duel_melee_swings: number
	sumo_duel_rounds_played: number
	sumo_duel_melee_hits: number
	sumo_duel_wins: number
	sumo_duel_losses: number
	sumo_duel_deaths: number
	duels_chests: number
	Duels_openedChests: number
	Duels_openedRares: number
	duels_chest_history: string[]
	Duels_openedCommons: number
	Duels_openedEpics: number
	Duels_openedLegendaries: number
	active_auras: string
	mw_duel_melee_swings: number
	mw_duel_melee_hits: number
	mw_duel_damage_dealt: number
	mw_duel_bow_hits: number
	blitz_duel_layout_archer_5: DuelsInventoryLayout
	duels_winstreak_best_sumo_duel: number
	active_victory_dance: string
	sw_duels_kit_new: string
	active_killmessages: string
	sw_duel_layout_knight_5: DuelsInventoryLayout
	sw_tournament_losses: number
	sw_doubles_pyromancer_kit_wins: number
	sumo_duel_kills: number
	sumo_tournament_melee_hits: number
	sumo_tournament_melee_swings: number
	sumo_tournament_losses: number
	sumo_tournament_kills: number
	sumo_tournament_deaths: number
	sumo_tournament_rounds_played: number
	uhc_meetup_deaths: number
	uhc_meetup_losses: number
	uhc_meetup_rounds_played: number
	duels_winstreak_best_uhc_meetup: number
	uhc_meetup_wins: number
	uhc_meetup_health_regenerated: number
	uhc_meetup_melee_hits: number
	uhc_meetup_damage_dealt: number
	uhc_meetup_melee_swings: number
	reaper_kit_wins: number
	blitz_duel_kit_wins: number
	blitz_duel_reaper_kit_wins: number
	selected_1_new: string
	selected_2_new: string
	active_kill_effect: string
	active_weaponpacks: string
	duels_winstreak_best_null: number
	progress_mode: string
	no_debuff_godlike_title_prestige: number
	mega_walls_legend_title_prestige: number
	op_diamond_title_prestige: number
	classic_diamond_title_prestige: number
	mega_walls_rookie_title_prestige: number
	blitz_diamond_title_prestige: number
	mega_walls_master_title_prestige: number
	mega_walls_diamond_title_prestige: number
	bow_godlike_title_prestige: number
	no_debuff_legend_title_prestige: number
	bow_rookie_title_prestige: number
	classic_godlike_title_prestige: number
	no_debuff_rookie_title_prestige: number
	classic_legend_title_prestige: number
	combo_iron_title_prestige: number
	bow_gold_title_prestige: number
	bow_diamond_title_prestige: number
	op_godlike_title_prestige: number
	no_debuff_diamond_title_prestige: number
	tournament_legend_title_prestige: number
	sumo_gold_title_prestige: number
	classic_master_title_prestige: number
	combo_godlike_title_prestige: number
	tournament_master_title_prestige: number
	op_gold_title_prestige: number
	tournament_diamond_title_prestige: number
	blitz_iron_title_prestige: number
	skywars_godlike_title_prestige: number
	tnt_games_master_title_prestige: number
	tournament_gold_title_prestige: number
	tnt_games_godlike_title_prestige: number
	skywars_rookie_title_prestige: number
	blitz_rookie_title_prestige: number
	tournament_iron_title_prestige: number
	sumo_legend_title_prestige: number
	tnt_games_gold_title_prestige: number
	all_modes_iron_title_prestige: number
	sumo_diamond_title_prestige: number
	classic_gold_title_prestige: number
	sumo_iron_title_prestige: number
	mega_walls_gold_title_prestige: number
	uhc_rookie_title_prestige: number
	blitz_legend_title_prestige: number
	all_modes_godlike_title_prestige: number
	sumo_godlike_title_prestige: number
	uhc_master_title_prestige: number
	all_modes_diamond_title_prestige: number
	uhc_godlike_title_prestige: number
	skywars_iron_title_prestige: number
	uhc_legend_title_prestige: number
	uhc_iron_title_prestige: number
	op_master_title_prestige: number
	combo_legend_title_prestige: number
	sumo_rookie_title_prestige: number
	uhc_diamond_title_prestige: number
	classic_rookie_title_prestige: number
	all_modes_gold_title_prestige: number
	no_debuff_iron_title_prestige: number
	tnt_games_legend_title_prestige: number
	classic_iron_title_prestige: number
	skywars_diamond_title_prestige: number
	tnt_games_rookie_title_prestige: number
	tnt_games_iron_title_prestige: number
	all_modes_master_title_prestige: number
	skywars_gold_title_prestige: number
	mega_walls_iron_title_prestige: number
	skywars_legend_title_prestige: number
	blitz_gold_title_prestige: number
	no_debuff_gold_title_prestige: number
	mega_walls_godlike_title_prestige: number
	tnt_games_diamond_title_prestige: number
	no_debuff_master_title_prestige: number
	combo_diamond_title_prestige: number
	blitz_godlike_title_prestige: number
	combo_rookie_title_prestige: number
	combo_gold_title_prestige: number
	op_iron_title_prestige: number
	all_modes_rookie_title_prestige: number
	bow_master_title_prestige: number
	sumo_master_title_prestige: number
	skywars_master_title_prestige: number
	op_legend_title_prestige: number
	tournament_godlike_title_prestige: number
	tournament_rookie_title_prestige: number
	bow_legend_title_prestige: number
	all_modes_legend_title_prestige: number
	bow_iron_title_prestige: number
	uhc_gold_title_prestige: number
	op_rookie_title_prestige: number
	blitz_master_title_prestige: number
	combo_master_title_prestige: number
	golem_kit_wins: number
	blitz_duel_golem_kit_wins: number
	knight_kit_wins: number
	blitz_duel_knight_kit_wins: number
	blitz_duel_layout_jockey_5: DuelsInventoryLayout
	blitz_duel_jockey_kit_wins: number
	jockey_kit_wins: number
	sw_duel_blacksmith_kit_wins: number
	blacksmith_kit_wins: number
	sw_duel_layout_blacksmith_5: DuelsInventoryLayout
	uhc_meetup_bow_shots: number
	uhc_meetup_bow_hits: number
	rambo_kit_wins: number
	blitz_duel_rambo_kit_wins: number
	creepertamer_kit_wins: number
	blitz_duel_creepertamer_kit_wins: number
	tournament_grandmaster_title_prestige: number
	classic_grandmaster_title_prestige: number
	mega_walls_grandmaster_title_prestige: number
	op_grandmaster_title_prestige: number
	blitz_grandmaster_title_prestige: number
	bow_grandmaster_title_prestige: number
	tnt_games_grandmaster_title_prestige: number
	all_modes_grandmaster_title_prestige: number
	sumo_grandmaster_title_prestige: number
	no_debuff_grandmaster_title_prestige: number
	combo_grandmaster_title_prestige: number
	uhc_grandmaster_title_prestige: number
	skywars_grandmaster_title_prestige: number
	sw_tournament_wins: number
	custom_titles: string[]
	equipped_custom_titles: string
	new_titles_applied: boolean
	special_test_title: boolean
	maps_won_on: string[]
	sw_duels_kit_new2: string
	special_godlike: boolean
	sw_duel_champion_kit_wins: number
	champion_kit_wins: number
	collected_rewards_season_1: boolean
	collected_rewards_season_2: boolean
	collected_rewards_season_3: boolean
	collected_reward_season_3: boolean
	blocks_placed: number
	uhc_duel_blocks_placed: number
	mw_duel_enderman_kit_wins: number
	meters_travelled_standard: number
	mw_duel_kit_wins: number
	meters_travelled: number
	enderman_meters_travelled_standard: number
	mw_duel_wins: number
	enderman_a_meters_travelled_standard: number
	enderman_a_meters_travelled: number
	enderman_kit_wins: number
	enderman_meters_travelled: number
	mw_duel_kills: number
	sw_duel_blocks_placed: number
	golden_apples_eaten: number
	combo_duel_golden_apples_eaten: number
	blitz_duel_blocks_placed: number
	sw_tournament_blocks_placed: number
	uhc_duel_golden_apples_eaten: number
	mw_doubles_wins: number
	mw_doubles_kit_wins: number
	mw_doubles_enderman_kit_wins: number
	bridge_rookie_title_prestige: number
	bridge_2v2_wins: number
	bridge_2v2_rounds_played: number
	layout_mw_duel_layout_shaman: DuelsInventoryAlternateLayout
	layout_blitz_duel_layout_shadow_knight: DuelsInventoryAlternateLayout
	layout_sw_duel_layout_scout: DuelsInventoryAlternateLayout
	layout_bow_duel_layout: DuelsInventoryAlternateLayout
	bridge_1v1_losses: number
	bridge_1v1_rounds_played: number
	bridge_1v1_deaths: number
	bridgeMapWins: string[]
	bridge_1v1_wins: number
	duels_winstreak_best_bridge_1v1: number
	bridge_1v1_blocks_placed: number
	bridge_1v1_bow_shots: number
	bridge_1v1_melee_hits: number
	bridge_1v1_damage_dealt: number
	bridge_1v1_melee_swings: number
	bridge_1v1_health_regenerated: number
	bridge_godlike_title_prestige: number
	leaderboardPage_goals: number
	best_bridge_winstreak: number
	best_overall_winstreak: number
	current_bridge_winstreak: number
	current_winstreak: number
	current_winstreak_bridge: number
	bridge_1v1_goals: number
	goals: number
	leaderboardPage_wins: number
	layout_sw_duel_pyromancer: DuelsInventoryAlternateLayout
	bridge_duel_losses: number
	bridge_duel_goals: number
	bridge_duel_rounds_played: number
	bridge_duel_wins: number
	duels_winstreak_best_bridge_duel: number
	bridge_duel_melee_hits: number
	bridge_duel_melee_swings: number
	bridge_duel_damage_dealt: number
	bridge_duel_health_regenerated: number
	bridge_duel_blocks_placed: number
	bridge_duel_bow_hits: number
	bridge_duel_bow_shots: number
	sumo_tournament_wins: number
	bridge_2v2v2v2_goals: number
	bridge_2v2v2v2_losses: number
	bridge_2v2v2v2_health_regenerated: number
	bridge_2v2v2v2_blocks_placed: number
	bridge_2v2v2v2_rounds_played: number
	bridge_2v2v2v2_melee_swings: number
	bridge_2v2v2v2_bow_hits: number
	bridge_2v2v2v2_bow_shots: number
	bridge_2v2v2v2_melee_hits: number
	bridge_2v2v2v2_damage_dealt: number
	bridge_duel_kills: number
	bridge_duel_deaths: number
	'blitz_duel_shadow knight_kit_wins': number
	'shadow knight_kit_wins': number
	sw_doubles_blocks_placed: number
	bowspleef_duel_kills: number
	mw_duel_herobrine_kit_wins: number
	herobrine_kit_wins: number
	status_field: string
	bridge_four_rounds_played: number
	bridge_four_deaths: number
	bridge_four_goals: number
	bridge_four_wins: number
	bridge_four_losses: number
	bridge_four_kills: number
	bridge_doubles_wins: number
	bridge_doubles_rounds_played: number
	bridge_doubles_losses: number
	bridge_doubles_deaths: number
	bridge_doubles_kills: number
	bridge_doubles_goals: number
	bridge_doubles_damage_dealt: number
	bridge_doubles_blocks_placed: number
	bridge_doubles_melee_swings: number
	bridge_doubles_melee_hits: number
	bridge_four_damage_dealt: number
	bridge_four_melee_swings: number
	bridge_four_melee_hits: number
	active_goal: string
	active_glyph: string
	bridge_tournament_rounds_played: number
	bridge_tournament_losses: number
	bridge_tournament_bow_shots: number
	bridge_tournament_kills: number
	bridge_tournament_damage_dealt: number
	bridge_tournament_melee_hits: number
	bridge_tournament_bow_hits: number
	bridge_tournament_melee_swings: number
	bridge_tournament_deaths: number
	bridge_tournament_health_regenerated: number
	bridge_tournament_blocks_placed: number
	bridge_tournament_goals: number
	current_winstreak_mode_sw_doubles: number
	current_skywars_winstreak: number
	best_winstreak_mode_sw_doubles: number
	best_skywars_winstreak: number
	current_winstreak_mode_blitz_duel: number
	current_blitz_winstreak: number
	best_winstreak_mode_sw_duel: number
	current_winstreak_mode_sw_duel: number
	best_uhc_winstreak: number
	best_winstreak_mode_uhc_duel: number
	current_winstreak_mode_uhc_duel: number
	current_uhc_winstreak: number
	current_winstreak_mode_bridge_duel: number
	best_winstreak_mode_bridge_duel: number
	leaderboardPage_win_streak: number
	best_winstreak_mode_uhc_doubles: number
	current_winstreak_mode_uhc_doubles: number
	uhc_doubles_golden_apples_eaten: number
	best_winstreak_mode_bridge_four: number
	current_winstreak_mode_bridge_four: number
	duels_winstreak_best_bridge_four: number
	current_tnt_games_winstreak: number
	best_winstreak_mode_bowspleef_duel: number
	best_tnt_games_winstreak: number
	current_winstreak_mode_bowspleef_duel: number
	layout_sw_duel_champion: DuelsInventoryAlternateLayout
	bridge_duel_bridge_deaths: number
	bridge_duel_bridge_kills: number
	bridge_kills: number
	bridge_deaths: number
	bridge_tournament_bridge_kills: number
	bridge_tournament_bridge_deaths: number
	best_op_winstreak: number
	current_op_winstreak: number
	best_winstreak_mode_op_doubles: number
	current_winstreak_mode_op_doubles: number
	best_winstreak_mode_bridge_doubles: number
	current_winstreak_mode_bridge_doubles: number
	best_bow_winstreak: number
	best_winstreak_mode_bow_duel: number
	current_winstreak_mode_bow_duel: number
	current_bow_winstreak: number
	best_blitz_winstreak: number
	best_winstreak_mode_blitz_duel: number
	grenade_kit_wins: number
	sw_duel_grenade_kit_wins: number
	blitz_duel_horsetamer_kit_wins: number
	horsetamer_kit_wins: number
	uhc_meetup_blocks_placed: number
	blitz_duel_slimeyslime_kit_wins: number
	slimeyslime_kit_wins: number
	best_winstreak_mode_bridge_3v3v3v3: number
	current_winstreak_mode_bridge_3v3v3v3: number
	bridge_3v3v3v3_bow_hits: number
	bridge_3v3v3v3_melee_hits: number
	bridge_3v3v3v3_blocks_placed: number
	bridge_3v3v3v3_melee_swings: number
	bridge_3v3v3v3_bridge_deaths: number
	bridge_3v3v3v3_bow_shots: number
	bridge_3v3v3v3_rounds_played: number
	bridge_3v3v3v3_health_regenerated: number
	bridge_3v3v3v3_wins: number
	bridge_3v3v3v3_bridge_kills: number
	bridge_3v3v3v3_goals: number
	bridge_3v3v3v3_damage_dealt: number
	bridge_doubles_bridge_deaths: number
	bridge_doubles_bridge_kills: number
	bridge_doubles_health_regenerated: number
	bridge_doubles_bow_shots: number
	bridge_doubles_bow_hits: number
	layout_blitz_duel_slimeyslime: DuelsInventoryAlternateLayout
	layout_combo_duel_layout: DuelsInventoryAlternateLayout
	best_winstreak_mode_sumo_duel: number
	current_winstreak_mode_sumo_duel: number
	best_sumo_winstreak: number
	current_sumo_winstreak: number
	active_cage: string
	best_winstreak_mode_op_duel: number
	current_winstreak_mode_op_duel: number
	sw_duels_kit_new3: string
	best_winstreak_mode_uhc_meetup: number
	current_winstreak_mode_uhc_meetup: number
	uhc_meetup_kills: number
	pingPreference: number
	equipped_ranked_titles: number
	Duels_new_ranked__2_2019_uhc_duel_stars: number
	ranked_streak_uhc_duel: number
	Duels_new_ranked__2_2019_ranked_1_stars: number
	ranked_1_melee_swings: number
	ranked_1_melee_hits: number
	ranked_1_damage_dealt: number
	ranked_1_rounds_played: number
	best_winstreak_mode_ranked_1: number
	ranked_streak_ranked_1: number
	ranked_loss_streak_ranked_1: number
	current_winstreak_mode_ranked_1: number
	Duels_new_ranked__2_2019_ranked_1_bestStars: number
	ranked_1_wins: number
	ranked_1_kills: number
	duels_winstreak_best_ranked_1: number
	sw_duel_armorer_kit_wins: number
	armorer_kit_wins: number
	duels_recently_played2: string
	Duels_new_ranked__2_2019_overallBestStars: number
	Duels_new_ranked__2_2019_ranked_1_bestElo: number
	ranked_1_losses: number
	Duels_Duels_new_ranked__3_2019_ranked_1_bestStars: number
	Duels_Duels_new_ranked__3_2019_overallBestStars: number
	Duels_new_ranked__3_2019_overallBestStars: number
	Duels_new_ranked__3_2019_ranked_1_bestStars: number
	ranked_1_health_regenerated: number
	ranked_1_deaths: number
	ranked_1_bow_shots: number
	ranked_1_bow_hits: number
	ranked_1_golden_apples_eaten: number
	Duels_new_ranked__3_2019_ranked_1_bestElo: number
	Duels_new_ranked__3_2019_ranked_1_maxStars: boolean
	best_winstreak_mode_mw_doubles: number
	current_mega_walls_winstreak: number
	best_mega_walls_winstreak: number
	current_winstreak_mode_mw_doubles: number
	duels_winstreak_best_mw_doubles: number
	season_1_reward_fix: boolean
	season_1_reward_fixes: boolean
	collected_reward_season_1: boolean
	Duels_new_ranked__4_2019_overallBestStars: number
	Duels_new_ranked__4_2019_ranked_1_bestStars: number
	Duels_new_ranked__4_2019_ranked_1_maxStars: boolean
	Duels_new_ranked__4_2019_ranked_1_bestElo: number
	archer_kit_wins: number
	blitz_duel_archer_kit_wins: number
	ranked_1_goals: number
	ranked_1_bridge_deaths: number
	collected_reward_season_2: boolean
	current_classic_winstreak: number
	best_classic_winstreak: number
	Duels_new_ranked__6_2019_ranked_1_maxStars: boolean
	Duels_new_ranked__6_2019_overallBestStars: number
	Duels_new_ranked__6_2019_ranked_1_bestElo: number
	Duels_new_ranked__6_2019_ranked_1_bestStars: number
	current_winstreak_mode_uhc_four: number
	best_winstreak_mode_uhc_four: number
	sw_duel_scout_kit_wins: number
	current_winstreak_mode_mw_duel: number
	best_winstreak_mode_mw_duel: number
	collected_reward_season_4: boolean
	blitz_duel_donkeytamer_kit_wins: number
	donkeytamer_kit_wins: number
	heal_pots_used: number
	potion_duel_damage_dealt: number
	potion_duel_heal_pots_used: number
	potion_duel_health_regenerated: number
	potion_duel_melee_hits: number
	potion_duel_melee_swings: number
	potion_duel_rounds_played: number
	layout_bridge_duel_layout: DuelsInventoryAlternateLayout
	show_map_detail: string
	old_winstreak: number
	boxing_rookie_title_prestige: number
	parkour_rookie_title_prestige: number
	moved_to_redis: boolean
	duel_arena_bow_hits: number
	duel_arena_bow_shots: number
	duel_arena_damage_dealt: number
	duel_arena_deaths: number
	duel_arena_health_regenerated: number
	duel_arena_losses: number
	duel_arena_melee_hits: number
	duel_arena_melee_swings: number
	duel_arena_rounds_played: number
	duel_arena_kills: number
	duel_arena_wins: number
	moved_to_redis2: boolean
	capture_duel_bridge_deaths: number
	capture_duel_losses: number
	capture_duel_melee_swings: number
	capture_duel_rounds_played: number
	active_cosmetictitle: string
	parkour_eight_deaths: number
	parkour_eight_losses: number
	parkour_eight_rounds_played: number
	parkour_eight_wins: number
	moved_to_redis3: boolean
	toggle_proj_trail: string
	moved_to_redis_2: boolean
	bridge_diamond_title_prestige: number
	equipped_prefix_color: string
	bridge_duel_golden_apples_eaten: number
	best_all_modes_winstreak: number
	best_combo_winstreak: number
	best_boxing_winstreak: number
	best_parkour_winstreak: number
	best_no_debuff_winstreak: number
	best_arena_winstreak: number
	potion_duel_wins: number
	tnt_duel_wins: number
	boxing_duel_wins: number
	parkour_duel_wins: number
	boxing_diamond_title_prestige: number
	best_winstreak_mode_classic_duel: number
	current_winstreak_mode_classic_duel: number
	moved_to_redis_3: boolean
	best_winstreak_mode_potion_duel: number
	best_winstreak_mode_boxing_duel: number
	best_winstreak_mode_bridge_2v2v2v2: number
	best_winstreak_mode_combo_duel: number
	best_winstreak_mode_capture_threes: number
	best_winstreak_mode_duel_arena: number
	best_winstreak_mode_parkour_eight: number
	best_winstreak_mode_bridge_threes: number
}

/**
 * How inventory layouts are formatted in duels. Note that some inventories are
 * a little different, see `DuelsInventoryAlternateLayout` for that.
 * 
 * The key is a number representing the inventory position; 0-8 are the hotbar.
 * The value is formatted as {item id},{damage},{amount},{extra}.
 * The extra will either be empty, or have enchantments formatted as
 * `e:DIG_SPEED` or `e:DAMAGE_ALLe:FIRE_ASPECT` if there's multiple.

 */
export interface DuelsInventoryLayout {
	[key: number]: `${number},${number},${number},${string}`
}

/**
 * Sometimes layouts are formatted like this for some reason. The value can
 * either be a number id (like iron_sword) or something like `layout_scout2`. I
 * don't know what the latter means.
 */
export interface DuelsInventoryAlternateLayout {
	[key: number]: string | `layout_${string}${number}`
}
