import { GameInventory } from './_inventory'

export type SkyWarsKit =
	| 'default' // this isn't a kit, but it's treated as one in the api for some reason
	| 'armorsmith'
	| 'ecologist'
	| 'enchanter'
	| 'rookie'
	| 'batguy'
	| 'disco'
	| 'energix'
	| 'frog'
	| 'grenade'
	| 'healer'
	| 'scout'
	| 'cactus'
	| 'armorer'
	| 'baseball-player'
	| 'enderchest'
	| 'farmer'
	| 'fisherman'
	| 'hunter'
	| 'knight'
	| 'pharaoh'
	| 'snowman'
	| 'speleologist'
	| 'princess'
	| 'engineer'
	| 'pig-rider'
	| 'sloth'
	| 'magician'
	| 'warlock'
	| 'cannoneer'
	| 'enderman'
	| 'pyro'
	| 'troll'
	| 'guardian'
	| 'salmon'
	| 'slime'
	| 'jester'
	| 'zookeeper'
	| 'archeologist'

export type SkyWarsMegaKit =
	| 'default'
	| 'armorer'
	| 'armorsmith'
	| 'baseball-player'
	| 'cannoneer'
	| 'healer'
	| 'hunter'
	| 'knight'
	| 'paladin'
	| 'scout'
	| 'skeletor'
	| 'witch'
	| 'hellhound'
	| 'fisherman'
	| 'pyromaniac'
	| 'enderman'

export type SkyWarsRankedKit =
	| 'default'
	| 'armorer'
	| 'athlete'
	| 'blacksmith'
	| 'bowman'
	| 'champion'
	| 'healer'
	| 'hound'
	| 'magician'
	| 'paladin'
	| 'pyromancer'
	| 'scout'

type PartialStat =
	| 'killstreak'
	| 'winstreak'
	| 'survived_players'
	| 'wins'
	| 'fastest_win'
	| 'losses'
	| 'kills'
	| 'void_kills'
	| 'melee_kills'
	| 'most_kills_game'
	| 'assists'
	| 'deaths'
	| 'games'
	| 'chests_opened'
	| 'arrows_shot'
	| 'arrows_hit'
	| 'longest_bow_shot'
	| 'longest_bow_kill'
	| 'time_played'

// SkyWars has a ton of stats for every game and mode, we don't want to
// manually type them so they're autogenerated here

type NumberStats = {
	[key in
		| PartialStat
		| `${PartialStat}_solo`
		| `${PartialStat}_team`
		// normal
		| `${PartialStat}_solo_normal`
		| `${PartialStat}_team_normal`
		| `${PartialStat}_kit_enderchest_solo_enderchest`
		| `${PartialStat}_kit_basic_solo_${SkyWarsKit}`
		| `${PartialStat}_kit_advanced_solo_${SkyWarsKit}`
		| `${PartialStat}_kit_attacking_team_${SkyWarsKit}`
		// insane
		| `${PartialStat}_solo_insane`
		| `${PartialStat}_team_insane`
		// lab
		| `${PartialStat}_lab_kit_advanced_solo_${SkyWarsKit}`
		| `${PartialStat}_lab_kit_mining_team_${SkyWarsKit}`
		| `${PartialStat}_lab`
		| `${PartialStat}_lab_solo`
		| `${PartialStat}_lab_team`
		// mega
		| `kit_mega_mega_${SkyWarsMegaKit}`
		| `${PartialStat}_mega`
		| `${PartialStat}_mega_normal`
		| `${PartialStat}_mega_doubles`
		| `${PartialStat}_mega_doubles_normal`
		| `${PartialStat}_kit_mega_mega_${SkyWarsMegaKit}`
		// ranked
		| `${PartialStat}_ranked`
		| `${PartialStat}_ranked_normal`
		| `${PartialStat}_kit_ranked_ranked_${SkyWarsRankedKit}`]?: number
}

export type SkyWarsStats = NumberStats & {
	coins: number
	packages?: string[]

	/** The `winstreak` field might be more correct. */
	win_streak: number
	highestWinstreak: number

	quits: number
	quits_lab: number

	blocks_broken: number
	blocks_broken_lab?: number

	blocks_placed: number
	blocks_placed_lab: number

	souls_gathered: number
	souls_gathered_lab?: number

	bow_kills_lab?: number
	bow_kills_lab_solo?: number

	mob_kills_lab?: number
	mob_kills_lab_solo?: number
	mob_kills_lab_team?: number

	kills_monthly_a: number
	kills_monthly_b: number
	kills_weekly_a: number
	kills_weekly_b: number

	slime_explained?: number
	/** A UNIX timestamp. */
	slime_explained_last?: number

	lucky_explained?: number
	/** A UNIX timestamp. */
	lucky_explained_last?: number

	tnt_madness_explained?: number
	/** A UNIX timestamp. */
	tnt_madness_explained_last: number

	floor_is_lava_explained?: number
	/** A UNIX timestamp. */
	floor_is_lava_explained_last?: number

	rush_explained?: number
	/** A UNIX timestamp. */
	rush_explained_last?: number

	blizzard_explained?: number
	/** A UNIX timestamp. */
	blizzard_explained_last?: number

	hunters_vs_beasts_explained?: number
	/** A UNIX timestamp. */
	hunters_vs_beasts_explained_last?: number

	egg_thrown: number

	free_event_key_skywars_christmas_boxes_2019?: true
	usedSoulWell: boolean

	skywars_chest_history?: string[]

	SkyWars_openedChests?: number
	SkyWars_openedCommons?: number
	SkyWars_openedRares?: number

	votes_Siege?: number
	votes_Frostbite?: number
	votes_Elven?: number
	votes_Congo?: number
	votes_Toadstool?: number
	votes_Aqueduct?: number
	votes_MegaShire?: number
	'votes_Dwarf Fortress'?: number
	votes_Eirene?: number

	souls: number
	soul_well: number
	paid_souls: number

	activeCage: string
	items_enchanted?: number
	enderpearls_thrown?: number
	soul_well_rares: number
	solo_resistance_boost: number

	activeKit_SOLO?: string
	activeKit_TEAM?: string
	activeKit_MEGA?: string
	activeKit_RANKED?: string
	activeKit_TEAMS?: string
	activeKit_MEGA_DOUBLES_random?: boolean
	activeKit_MEGA_DOUBLES?: string
	activeKit_MEGA_random?: boolean
	activeKit_SOLO_random?: boolean
	activeKit_TEAMS_random?: boolean

	solo_mining_expertise?: number
	solo_arrow_recovery?: number
	solo_instant_smelting?: number
	solo_bulldozer?: number
	solo_ender_mastery?: number
	solo_juggernaut?: number
	solo_speed_boost?: number
	solo_marksmanship?: number
	solo_knowledge?: number
	solo_nourishment?: number
	solo_fat?: number
	solo_blazing_arrows?: number
	solo_revenge?: number
	'solo_annoy-o-mite'?: number
	solo_environmental_expert?: number
	solo_lucky_charm?: number
	solo_bridger?: number

	team_resistance_boost?: number
	team_ender_mastery?: number
	team_instant_smelting?: number
	team_mining_expertise?: number
	team_speed_boost?: number
	team_blazing_arrows?: number
	team_juggernaut?: number
	team_knowledge?: number
	team_arrow_recovery?: number
	team_fat?: number
	team_marksmanship?: number
	team_nourishment?: number
	'team_annoy-o-mite'?: number
	team_bridger?: number
	team_environmental_expert?: number
	team_lucky_charm?: number
	team_bulldozer?: number
	team_savior?: number

	mega_rusher?: number
	mega_ender_mastery?: number
	mega_tank?: number
	mega_mining_expertise?: number
	mega_notoriety?: number
	mega_nourishment?: number
	mega_juggernaut?: number
	mega_arrow_recovery?: number
	mega_blazing_arrows?: number
	mega_lucky_charm?: number
	mega_instant_smelting?: number
	mega_marksmanship?: number
	mega_environmental_expert?: number
	mega_bridger?: number

	activeDeathCry?: string
	activeVictoryDance?: string
	activeProjectileTrail?: string
	activeKillEffect?: string

	kit_mega_mega_armorer_inventory?: GameInventory
	kit_defending_team_armorer_inventory?: GameInventory
	kit_attacking_team_energix_inventory?: GameInventory
	kit_mega_mega_pyromaniac_inventory?: GameInventory
	kit_attacking_team_knight_inventory?: GameInventory
	kit_blacksmith_ranked_blacksmith_inventory?: GameInventory
	kit_mega_mega_witch_inventory?: GameInventory
	kit_mega_mega_scout_inventory?: GameInventory
	kit_ranked_ranked_pyromancer_inventory?: GameInventory
	kit_ranked_ranked_magician_inventory?: GameInventory
	kit_attacking_team_scout_inventory?: GameInventory
	kit_attacking_team_hunter_inventory?: GameInventory

	kit_attacking_team_energix_inventory_auto_equip_armor?: boolean
	kit_mega_mega_armorer_inventory_auto_equip_armor?: boolean
	lab_win_lucky_blocks_lab?: number
	lab_win_lucky_blocks_lab_solo?: number
	lab_win_lucky_blocks_lab_team?: number

	skywars_halloween_boxes?: number
	skywars_christmas_boxes?: number

	refill_chest_destroy?: number
	soul_well_legendaries?: number
	xezbeth_luck?: number
	highestKillstreak?: number
	extra_wheels?: number
	mystery_boxes_season_one?: number
	ranked_instant_smelting?: number
	harvesting_season?: number
	lastMode?: string
	games_played_skywars?: number
	win_streak_lab?: number
	coins_gained_lab?: number
	egg_thrown_lab?: number
	enderpearls_thrown_lab?: number

	inGamePresentsCap_2017_15?: number
	freeLootChestNpc?: number
	skywars_chests?: number
	cosmetic_tokens?: number
	kit_ranked_ranked_pyromancer_inventory_auto_equip_armor?: boolean
	skywars_easter_boxes?: number
	SkyWars_skywars_rating_8_18_rating?: number
	SkyWars_skywars_rating_8_18_position?: number
	beast_chance?: number
	skywars_experience?: number
	skywars_extra_time?: number
	levelFormatted?: string
	fall_kills?: number
	fall_kills_solo?: number
	lastTourneyAd?: number
}
